# Generated by Django 5.0.6 on 2024-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='last_checked',
            field=models.DateTimeField(null=True),
        ),
    ]
