# Generated by Django 5.0.6 on 2024-08-17 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.CharField(max_length=100)),
                ('time', models.DurationField()),
                ('category', models.CharField(max_length=20)),
                ('round', models.CharField(max_length=20, null=True)),
                ('overall_position', models.PositiveIntegerField()),
                ('age_position', models.PositiveIntegerField(null=True)),
                ('gender_position', models.PositiveIntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('athlete', 'event', 'distance', 'round'), name='unique_performance'),
        ),
    ]
